apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: backend
spec:
  containers:
    - name: backend
      image: backend:latest
      imagePullPolicy: Never
      resources:
        requests:
          memory: '64Mi'
          cpu: '250m'
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 3000
          name: http
      env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: '5432'
        - name: DB_DATABASE
          value: posts
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
